development:
  adapter: postgresql
  database: weblubu_development
  host: localhost
  port: 5432
  pool: 5

test:
  adapter: postgresql
  database: weblubu_test
  port: 5432
  pool: 5

production:
  adapter: postgresql
  database: weblubu_production
  port: 5432
  pool: 5

